### ISSUE TITLE
option chapter.titles off cause NPE (DOS line endings)

### ISSUE THREAD

**Issue by acdean** [acdean/acdepub#8]
```
<?xml version='1.0' encoding='UTF-8'?>
<book>
<info>
<author>Virginia Woolf</author>
<title>Monday or Tuesday</title>
<date>1921</date>
<option name="chapter.titles" value="off"/>
</info>
```

```
java.lang.NullPointerException
	at me.koogy.acdepub.objects.AcdParser.extractAttributes(AcdParser.java:372)
	at me.koogy.acdepub.objects.AcdParser.parseOptions(AcdParser.java:123)
	at me.koogy.acdepub.objects.AcdParser.parseBook(AcdParser.java:71)
```

**Comment by acdean** [comment]
Fixed. was removing newlines, so i added carriage returns.

https://github.com/acdean/acdepub/commit/ea46ff7b88e10d8b14dd10992ab21a68d14b3ad8
